### ISSUE TITLE
NFL_Draftkings module does not exist

### ISSUE THREAD

**Issue by Nishkixs** [BenBrostoff/draft-kings-fun#33]
Hi,

I am running the command python optimize.py -pids ../../Downloads/DKSalaries.csv and getting 

NFL_Draftkings module does not exist. 

I'm new to python and coding in general but any guidance would be awesome. 

Best,
Nishon

**Comment by BenBrostoff** [comment]
@Nishkixs Hey there - did you try: 

```
pip install -r requirements.txt
```

This will install the necessary dependencies for this project. Also, you'll need `ortools` as well, and [you can find installation instructions here](https://developers.google.com/optimization/installing). 

Let me know if this helps at all.

**Comment by Nishkixs** [comment]
HI Ben,
Thanks for getting back to me. I  ran those commands and and am now getting a  `No module named requests_cache`

So I ran 
`sudo pip install requests` and `sudo -H pop install requests`. And got the following 

```
$ sudo pip install requests
The directory '/Users/nishonradhakrishnan/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/nishonradhakrishnan/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: requests in /Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg

~/Desktop/draft-kings/draft-kings-fun (master)$ sudo -H pip install requests
Requirement already satisfied: requests in /Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg
```

but im still getting the same error of ```No module named requests_cache```
when I run ```python optimize.py -pids ../../../Downloads/Template.csv ```

**Comment by BenBrostoff** [comment]
`requests_cache` is actually a separate module - did you try:

```
pip install requests_cache
```

Either way, the `requirements.txt` is clearly behind what's actually necessary, so I'll update it.

**Comment by Nishkixs** [comment]
Ben, 

Thanks so much it works! I appreciate your help. 

Best,
Nishon
