### ISSUE TITLE
NBA Lineups Design

### ISSUE THREAD

**Issue by chppppp** [BenBrostoff/draft-kings-fun#40]
Before I dive into making an attempt to provide some usefulness to this repo I just wanted to check whether my results are expected. 

When I optimize a NBA Roster I generally will have to ban some players in order to satisfy the DK position constraints (PG,SG,SF,PF,etc...). Is this expected behavior or should I always be getting a lineup that easily fits into my DK lineup? I pulled this roster today that does not fit into DK automagically (It is missing a guard)

+------------+------------------+------+--------------------+--------+------------+----------+--------+
| Position   | Player           | Team | Matchup            | Salary | Projection | vs. Avg. | Locked |
+------------+------------------+------+--------------------+--------+------------+----------+--------+
| SF         | LeBron James     | Cle  | Cle@Por 10:30PM ET | 9700   | 54.11      | 1.943    |        |
| PF/C (PF)  | Kevin Love       | Cle  | Cle@Por 10:30PM ET | 8100   | 42.05      | -0.153   |        |
| PG         | Mike Conley      | Mem  | Mem@OKC 08:00PM ET | 6900   | 37.68      | 2.001    |        |
| C          | Marc Gasol       | Mem  | Mem@OKC 08:00PM ET | 6800   | 36.98      | -1.231   |        |
| C          | Marcin Gortat    | Was  | Was@Bos 08:00PM ET | 6000   | 33.35      | 1.135    |        |
| PF/C (PF)  | Gorgui Dieng     | Min  | Hou@Min 08:00PM ET | 5400   | 29.62      | 2.206    |        |
| SF         | Maurice Harkless | Por  | Cle@Por 10:30PM ET | 4000   | 24.41      | 0.857    |        |
| SG/SF (SG) | Corey Brewer     | Hou  | Hou@Min 08:00PM ET | 3000   | 16.63      | 7.515    |        |
+-

**Comment by BenBrostoff** [comment]
I have noticed sometimes that if you just add players sequentially, DraftKings will put them in the "wrong" spot (assuming you're just searching and adding), but your example seems legitimate / I think this may have happened to me a while ago and I ignored it. 

Do you mind sending me the CSV so I can replicate and work on?

**Comment by chppppp** [comment]
[csvs.zip](https://github.com/BenBrostoff/draft-kings-fun/files/700378/csvs.zip)

**Comment by BenBrostoff** [comment]
Awesome, was able to replicate with your CSV. Going to work on fixing today.

**Comment by BenBrostoff** [comment]
@chppppp I think my most recent PR resolves this issue - I added a unit test using the data you gave me and entered a few contests this morning with no problem. There's now explicit limits guaranteeing at least 3 guards and 3 forwards (and setting a maximum of 4 guards, 4 forwards and 2 centers). Let me know if you encounter any more issues here. 

Also, re: your first post on this issue on helping out, going to add a few tasks I've been putting off for a while, so feel free to grab any of them or just pick something else you think would be interesting if you decide to contribute on this repo.

**Comment by BenBrostoff** [comment]
Closing this one since I've been using for a few contests over the last few days without issue 👍

**Comment by chppppp** [comment]
Sorry for the late reply. Your fix looks good. 

I'll take a peek at the to-do list.
