### ISSUE TITLE
Add college basketball

### ISSUE THREAD

**Issue by BenBrostoff** [BenBrostoff/draft-kings-fun#42]

**Comment by sedemmler** [comment]
Mind if I have a go at this? If so, any specifics you want to talk through? Or is this project somewhat abandoned? (I'm cross posting this basic thing in the college BB section, feel free to delete one of the comments when you respond.)

**Comment by BenBrostoff** [comment]
@sedemmler Absolutely, definitely take this one. This project is alive and well; saw you joined the Slack channel. Re: college basketball, it might be useful to refer to [@swanson's optimizer project](https://github.com/swanson/degenerate), which heavily influenced mine and has already implemented college basketball. You'll probably need to make changes to `optimizer.py` and `orm.py`. E-mail me any questions or post on this issue!

**Comment by sedemmler** [comment]
Perfect. I found the Slack channel after posting here. I'll take a look this week at @swanson's project and then try to knock something out this weekend. Unless it's necessary to jump on here, I'll probably stick to Slack for now. Thanks!

**Comment by sedemmler** [comment]
So, DraftKings has dropped all college sports from its slate of offerings. So I think we can safely close this issue.
