### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by BenBrostoff** [BenBrostoff/draft-kings-fun#43]
- [x] Use `assert_equal` instead of `assert` in `nosetest`
- [x] Show code coverage
- [ ] Separate tests by sport

**Comment by sedemmler** [comment]
Mind if I have a go at this? If so, any specifics you want to talk through? Or is this project somewhat abandoned? (I'm cross posting this basic thing in the college BB section, feel free to delete one of the comments when you respond.)

**Comment by sedemmler** [comment]
It's been so long I've gotten a bit too busy and committed to some other work. Sorry, man.

**Comment by BenBrostoff** [comment]
No problem @sedemmler
