### ISSUE TITLE
Lock and Vs_Avg use

### ISSUE THREAD

**Issue by chppppp** [BenBrostoff/draft-kings-fun#46]
If I set my vs_avg to a certain number and then I lock a player who is outside of that vs_avg, the player does not lock. 

Can the locking feature happen outside of the vs_avg constraint? 

Thanks!

**Comment by BenBrostoff** [comment]
@chppppp I'll take a look - thanks for letting me know!

**Comment by BenBrostoff** [comment]
@chppppp Great catch - this issue was actually impacting a bunch of other filters as well - they would just wipe out the locks. Now resolved I think 👍
