### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by elwill23** [BenBrostoff/draft-kings-fun#53]
Traceback (most recent call last):
  File "nfl/prepare_data.py", line 7, in <module>
    with open(dk_csv, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'data/current-salaries.csv'

**Comment by elwill23** [comment]
ok I figured it out you have to make a data folder

**Comment by BenBrostoff** [comment]
Thanks for pointing this out @elwill23  - [resolved with this commit](https://github.com/BenBrostoff/draft-kings-fun/commit/a23f766318ee55d9c84fa76694024a1438cf06be).
