### ISSUE TITLE
No matching distribution found for ortools==6.8.5452

### ISSUE THREAD

**Issue by adamdarr** [BenBrostoff/draft-kings-fun#81]
Running `python2 -m pip install -r requirements.txt` gives me the following error:

```
Could not find a version that satisfies the requirement ortools==6.8.5452 (from -r requirements.txt (line 11)) (from versions: 4.1.3717, 4.2.3724, 4.2.3758, 4.2.3790, 4.3.3802, 4.3.3803, 4.3.3805, 4.4.3842, 5.0.3919, 5.1.4045, 6.0.4217, 6.1.4333, 6.3.4430, 6.3.4431, 6.4.4495, 6.5.4527, 6.6.4656, 6.6.4659)
No matching distribution found for ortools==6.8.5452 (from -r requirements.txt (line 11))
```

Has anyone else run into this?

**Comment by BenBrostoff** [comment]
@adamdarr I get the same error. This PR was just merged in and I admittedly didn't test it since it passed the CI build. I'll roll this back 👍

**Comment by adamdarr** [comment]
@BenBrostoff Works now. Thanks.

**Comment by BenBrostoff** [comment]
[This is now working from this PR](https://github.com/BenBrostoff/draft-kings-fun/pull/87) and is Python3 compatible.
